### ISSUE TITLE
Undefined symbols for architecture arm64:   "_AFNetworkingOperationFailingURLResponseErrorKey", referenced from:       ___36-[SGImageCacheTask fetchRemoteImage]_block_invoke69 in SGImageCacheTask.o

### ISSUE THREAD

**Issue by schube** [seatgeek/SGImageCache#9] opened 2015-03-16 20:02 UTC
Hello!
I added SGImageCache to my podfile and perform ``pod install``.
Now, when I compile my project with XCode 6.2 I the the following error

    Undefined symbols for architecture arm64:
      "_AFNetworkingOperationFailingURLResponseErrorKey", referenced from:
          ___36-[SGImageCacheTask fetchRemoteImage]_block_invoke69 in SGImageCacheTask.o
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

Here is a screenshot (because of an NDA I had to blure out the project name):
![bildschirmfoto 2015-03-16 um 20 56 16](https://cloud.githubusercontent.com/assets/9572844/6675230/61c82020-cc1f-11e4-86e8-f93565edb3ea.jpg)

Here is my podfile:

    platform :ios, '8.0'
    use_frameworks!
    target 'XXXX' do
    pod 'Alamofire', '~> 1.1'
    pod 'SwiftyJSON', '2.1.3'
    pod 'SGImageCache'
    pod 'Pushwoosh', '~> 2.9'
    pod "ODSAccordionView"
    pod 'JLToast'
    end

It is not working with my iPhone 6 plus nor with the iOS simulator. 

As soon as I remove SGImageCache I can compile my project again. 
What am I doing wrong? Any help is highly appreciated. Thank you!

**Comment by sobri909** [comment] 2015-03-16 22:22
Curious. What happens if you take out SGImageCache but add in AFNetworking on its own?

**Comment by schube** [comment] 2015-03-17 07:17
This podfile works (it compiles)

    pod 'Alamofire', '~> 1.1'
    pod 'SwiftyJSON', '2.1.3'
    pod 'AFNetworking', '~> 2.5'
    pod 'Pushwoosh', '~> 2.9'
    pod "ODSAccordionView"
    pod 'JLToast'

So adding AFNetworking itself is no problem.
Adding both, AFNetworking and SGImageCache results in the same problem as in my original post (which makes sense, since SGImageCache itself has a dependency to AFNetworking which CocoaPods resolves).

Thank you,
Bernhard

**Comment by sobri909** [comment] 2015-03-21 12:26
So I built a test Swift project. The `Podfile` is thus:

```yaml
platform :ios, '8.0'
pod 'SGImageCache'
```

The bridging header is thus:

```objc
#import "SGImageCache.h"
```

And the `ViewController.swift` has this:

```swift
override func viewDidLoad() {
    super.viewDidLoad()
    SGImageCache.getImageForURL("https://farm8.staticflickr.com/7627/16838248596_26c29ce29a_z_d.jpg") { image in
        if image != nil {
            NSLog("%@", image)
        }
    }
}
```

And the project runs produces this output:

```
2015-03-21 20:22:53.711 SGImageCache-test[67636:1659548] <UIImage: 0x7fb0ba52e5c0>
```

So I can't find the problem yet. 

Can you make a test project that reproduces the problem? Thanks.

**Comment by lucaslain** [comment] 2015-03-24 12:47
@schube could you solve the problem ? Integrate SGImageCache to your project without problems?

**Comment by lucaslain** [comment] 2015-03-26 15:23
Remove ``use_frameworks!`` 

You might need to use AFNetworking instead of Alamofire (the reason you need the ``use_frameworks!`` tag). SGImageCache uses AFNetworking internally. 

Said this, I'd love to be able to use SGImageCache and Alamofire. I hope SG moves to Alamofire soon.

**Comment by lucaslain** [comment] 2015-04-02 17:10
You can also append this to the Podfile (force SGImage to use AFNetworking):

```
post_install do |installer_representation|
    installer_representation.project.targets.each do |target|
        if(target.name == 'Pods-SGImageCache')
            target.build_configurations.each do |config|
                config.build_settings['OTHER_LDFLAGS'] = '-framework AFNetworking'
            end
        end
    end
end
```

**Comment by adamdahan** [comment] 2015-04-08 20:41
So basically you can't use this project with projects that leverage Alamofire?

**Comment by adamdahan** [comment] 2015-04-08 20:42
Shame.

**Comment by adamdahan** [comment] 2015-04-09 00:31
Actually not a shame. Honestly this project uses 4 different dependencies to function. LOL. common. 

Removing AFNetworking
Removing MGEvents
Removing SGHTTPRequest
Removing SGImageCache

**Comment by sobri909** [comment] 2015-04-09 02:31
Alamofire is a Swift only thing, and Swift is barely ready for real world use, so I'm not personally in a rush to find an answer to this one. This is also an open source project, so anyone is welcome to find the answer themselves and contribute back.

> Honestly this project uses 4 different dependencies to function. 

3 dependencies. MGEvents and SGHTTPRequest are tiny, and AFNetworking is a standard package for Objective-C based projects. The MGEvents dependency isn't really necessary, but it really is minuscule.

**Comment by adamdahan** [comment] 2015-04-09 16:37
@sobri909 I understand, thanks for your project anyways :) It is still extremely useful for those not using Cocoa pods with Swift projects!

**Comment by staminajim** [comment] 2015-04-29 09:28
OK guys I think I've got the fix for this.  We'll push the update upstream shortly...

**Closed by staminajim** 2015-04-29 09:28 UTC
Labels: bug
